# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DH1PzdNQxUB/v4d1/j5v+ZvRxpdt8aW97scBTEgIhN9LLgBysS/bE4WqmPMiHhBXrO2aJ7/xBjF+r/wy87qHqwWgRxDUn4VmwnC8R/WTmtFqUJKzCAHMugP/2HHrR7Tf03I9E5ttI3ypFmmA3vIEfQsnvrmu/nDLq5JCDAZkyDLA9zK5MzKsW6iGXhmRTwP5/gurj7bFPoPq+CdJuK3Ic1vbItl8mjKPyH/M376Qqi9mVNOayVc7QfSEX2So4kczcB2JoUZFu/dolfdjT36c49q0vQbbmqBUOlCpM89IJP4pJFoBVd9bgugvh5mLN5mgwUikdq2bv/bkSSDWSAUJolrq9YxBjkRBSpINdOOcwxRDGjdAYnYBu74Ku5hm5/ZiQF1Vj1xfhCcFRmgH72a7Y5djp1bw/0+k1yu/ejDINky8PRkaD543iRanX1ch06x95vcw0QMF+/i3uS2v2UzqtJArQ/+BKHzxprDEMIY1ysl9QgYsv8/xYkTbzXTcCgOSPgQzDWXSIGXdsVBKhwkZ9sqa3jRn/PKCWJh+SNypozODqqA97iehPVpm+S+mGlk+PkIcybVzy6zw5j7FfXPED052p2d+7X9T6CSmJnq2ftw2ERSLp/xzuGJEj3gbcCm7YXzek7skVzQaB0b+WiS0m30ws3RLIojvXO9awhdP3w0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
