travis:
  secure:
    BINSTAR_TOKEN: VjPuuPHoF2yXrtymdgfkXxhpYJJArAP8KiKcyK471lSqe+G27XIexKEnYYaeO3BNAoUPgHFep6uEFGfhwflyJQPTh1vKb3sKOcBnNeOrHtJZKukw/smslliKzVHxyv3q9Qmoho9Q6+y3cC3G3v46sxfqNa0Coprof4kJVh6o5A5mlbka56eFbJCIbX8UHNCoig+wlb8aV/Jb7E8r2cOHDCEXOaJfBO3+CJkZHSLy0D9KmFeAhxY/PLib0TVmqqjiiXjZvfWDQCz2NSpoR25W14Qr34NZwtUANX/jYvW0Dl0EdRlXk0nyaxAv/JlKuTKuYFnZquX3GdxFKKqUd5AuKLz47FVO3GfzVxHfnf3TL3bYr1piQYBHjG8BQd1PEGFyEli6dlekQGYb53A9Yl3OUkBbxF8HiDvGK71edtD98iRirmtAhXulnR2NGIKzD9yvnh9dtu0+JQYhqE87gM7J+pegQTx9hAA2xWKYkZsIXWPmcqrpI0zD+sSVXoR96CeYTdn0ql7htkGspqVbk6Vt0iRthE667PzPwjeH0UBm6vplYCqh89tMaFlXdwgBTr60uNFm+O+5s/YidqXiHClXAIl1KTodKkCmvOrXbj3s7MSNAKLgeGi1ya/EJCz2+SItkYvm6C+9kzI4GBasOCQfCCZlAy8semREGjktvqO9X4Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
